services:
  - type: web
    name: tvs-video-frontend
    env: node
    buildCommand: cd frontend && npm install && NEXT_PUBLIC_API_URL=https://tvs-video-backend.onrender.com npm run build
    startCommand: cd frontend && npx next start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tvs-video-backend.onrender.com
      - key: ACCESS_PASSWORD
        value: tvs2024
